services:
  komari:
    image: ghcr.io/coolman1232004/komari-classic:v1.2.5-fix2-security.3.1@sha256:0a6f56e3fa6df3d917209b0a62424dba257c431fe1023bf6fcafe863fe3389ff
    container_name: komari-classic-security
    restart: unless-stopped
    ports:
      - "127.0.0.1:25775:25774"
    volumes:
      - komari-classic-security-data:/app/data
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  komari-classic-security-data:
